import { Quicksand } from "next/font/google";

import "./globals.css";

const quicksand = Quicksand({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Gemini Clone - Your AI Assistance",
  description: "Generated by Bharat Nagda",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
